title: Lucas Bader | n3ko1 # The title of the blog
author: Lucas Bader # Your name
email: lcs.bader@gmail.com # your email shown in the footer
url: https://www.lucas-bader.com # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  All things CTF, hacking and large-scale C++ development.

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  avatar_url: "https://avatars.githubusercontent.com/u/2579568?v=4"
  about_you: building things. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    github: n3ko1
    rss: RSS
    linkedin: lucas-bader-27247285
